// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Project struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Task struct {
	ID           int64
	ProjectID    int64
	ParentTaskID sql.NullInt64
	Content      string
	Link         sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	CompletedAt  sql.NullTime
}
