// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, parent_task_id, content, link)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, project_id, parent_task_id, content, link, created_at, updated_at, completed_at
`

type CreateTaskParams struct {
	ProjectID    int64
	ParentTaskID sql.NullInt64
	Content      string
	Link         sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ProjectID,
		arg.ParentTaskID,
		arg.Content,
		arg.Link,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Content,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const deleteTasksByProjectID = `-- name: DeleteTasksByProjectID :exec
DELETE FROM tasks WHERE project_id = ?1
`

func (q *Queries) DeleteTasksByProjectID(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByProjectID, projectID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, parent_task_id, content, link, created_at, updated_at, completed_at
FROM tasks
WHERE id = ?1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Content,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTasksByParentID = `-- name: GetTasksByParentID :many
SELECT id, project_id, parent_task_id, content, link, created_at, updated_at, completed_at
FROM tasks
WHERE parent_task_id = ?1
`

func (q *Queries) GetTasksByParentID(ctx context.Context, parentTaskID sql.NullInt64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByParentID, parentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentTaskID,
			&i.Content,
			&i.Link,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksOrdered = `-- name: GetTasksOrdered :many
SELECT id, project_id, parent_task_id, content, link, created_at, updated_at, completed_at
FROM tasks
ORDER BY project_id, CASE WHEN parent_task_id IS NULL THEN 0 ELSE 1 END, id
`

func (q *Queries) GetTasksOrdered(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentTaskID,
			&i.Content,
			&i.Link,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET content = ?1, link = ?2, completed_at = ?3, updated_at = CURRENT_TIMESTAMP
WHERE id = ?4
`

type UpdateTaskParams struct {
	Content     string
	Link        sql.NullString
	CompletedAt sql.NullTime
	ID          int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Content,
		arg.Link,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
