// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, parent_task_id, content, link)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, project_id, parent_task_id, content, link, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID    int64
	ParentTaskID sql.NullInt64
	Content      string
	Link         sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ProjectID,
		arg.ParentTaskID,
		arg.Content,
		arg.Link,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Content,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTasksOrdered = `-- name: GetTasksOrdered :many
SELECT id, project_id, parent_task_id, content, link, created_at, updated_at 
FROM tasks 
ORDER BY project_id, CASE WHEN parent_task_id IS NULL THEN 0 ELSE 1 END, id
`

func (q *Queries) GetTasksOrdered(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentTaskID,
			&i.Content,
			&i.Link,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks 
SET content = ?1, link = ?2, updated_at = CURRENT_TIMESTAMP 
WHERE id = ?3
`

type UpdateTaskParams struct {
	Content string
	Link    sql.NullString
	ID      int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask, arg.Content, arg.Link, arg.ID)
	return err
}
